### ISSUE TITLE
[Bug] Hitscan 및 Projectile 오류

### ISSUE THREAD

**Issue by dkdace** [dkdace/dmgr-server#41]
## ℹ Description
getNearEnemy의 null 반환으로 인한 NPE 오류 발생

## ⚠ To reproduce
버그 발생 과정에 대한 설명
1. 전투원 '아케이스' 선택
2. 무기 및 1번 스킬 사용

## ✅ Tasks
- [x] 오류 해결

## 💬 Comment
--

**Comment by DoubleDeltas** [comment]
Entry<null, false>를 return 했어야했는데 그냥 null을 return했었네요
ㄱㄷ 올리겠음
